import pytest
import os
import subprocess
import glob
import difflib

# Paths
TESTS_ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.abspath(os.path.join(TESTS_ROOT_DIR, "../src"))
TESTS_PROGRAMS_DIR = os.path.join(TESTS_ROOT_DIR, "programs")
EXECUTABLE = os.path.join(SRC_DIR, "danac")

def run_command(command, input_text=None, cwd=SRC_DIR):
    try:
        result = subprocess.run(
            command,
            input=input_text,
            capture_output=True,
            text=True,
            shell=True,
            cwd=cwd
        )
        return result.returncode, result.stdout, result.stderr
    except Exception as e:
        return -1, "", str(e)

@pytest.fixture(scope="session")
def compiler():
    prebuilt_path = os.environ.get("CI_PREBUILT_EXECUTABLE")
    if prebuilt_path:
        # Resolve path if it's relative
        if not os.path.isabs(prebuilt_path):
             prebuilt_path = os.path.abspath(os.path.join(SRC_DIR, prebuilt_path))
             
        print(f"\nUsing prebuilt compiler at: {prebuilt_path}")
        if not os.path.exists(prebuilt_path):
            pytest.fail(f"Prebuilt compiler not found at {prebuilt_path}")
        yield prebuilt_path
        return

    print("\nBuilding compiler...")
    # Clean first to ensure fresh build
    ret, out, err = run_command("make clean && make", cwd=SRC_DIR)
    if ret != 0:
        pytest.fail(f"Build failed:\n{err}")
    
    if not os.path.exists(EXECUTABLE):
        pytest.fail(f"Executable '{EXECUTABLE}' not found after build.")
    
    yield EXECUTABLE

# Test 1: Compiler Build
def test_compiler_build(compiler):
    """
    Verifies that the compiler built successfully.
    The 'compiler' fixture does the work; this test just confirms it.
    """
    assert os.path.exists(compiler), "Compiler executable is missing."

def get_test_files():
    if not os.path.isdir(TESTS_PROGRAMS_DIR):
        return []
    return sorted(glob.glob(os.path.join(TESTS_PROGRAMS_DIR, "*.dana")))

# Test 2..N: Program Tests
@pytest.mark.parametrize("dana_file", get_test_files(), ids=lambda x: os.path.basename(x))
def test_dana_program(compiler, dana_file):
    base_name = os.path.splitext(os.path.basename(dana_file))[0]
    input_file = os.path.join(TESTS_PROGRAMS_DIR, base_name + ".input")
    result_file = os.path.join(TESTS_PROGRAMS_DIR, base_name + ".result")

    # 1. Compilation
    cmd_compile = f'"{compiler}" "{dana_file}"'
    ret, out, err = run_command(cmd_compile, cwd=SRC_DIR)
    
    if ret != 0:
        pytest.fail(f"Compilation failed for {base_name}:\nStdout: {out}\nStderr: {err}")

    # Check for a.out
    # Note: main.cpp hardcodes output to "a.out" in CWD
    a_out = os.path.join(SRC_DIR, "a.out")
    if not os.path.exists(a_out):
        pytest.fail(f"Compilation reported success but 'a.out' not found for {base_name}.")

    try:
        # 2. Correctness (Runtime)
        stdin_input = ""
        if os.path.exists(input_file):
            with open(input_file, 'r') as f:
                stdin_input = f.read()
        
        # Run generated executable
        ret, out, err = run_command("./a.out", input_text=stdin_input, cwd=SRC_DIR)

        if ret < 0: # Signal 
             pytest.fail(f"Runtime crash (signal {-ret}) for {base_name}.\nStderr: {err}")
        
        if os.path.exists(result_file):
            with open(result_file, 'r') as f:
                expected_output = f.read()
            
            actual_stripped = out.strip()
            expected_stripped = expected_output.strip()

            if actual_stripped != expected_stripped:
                diff = list(difflib.unified_diff(
                    expected_stripped.splitlines(),
                    actual_stripped.splitlines(),
                    fromfile='expected',
                    tofile='actual',
                    lineterm=''
                ))
                diff_text = "\n".join(diff)
                pytest.fail(f"Output mismatch for {base_name}:\n{diff_text}")

    finally:
        # Cleanup a.out
        if os.path.exists(a_out):
            os.remove(a_out)
        # Cleanup intermediate files generated by compiler in program dir
        exts = [".imm", ".asm", ".o"]
        for ext in exts:
            f = os.path.join(TESTS_PROGRAMS_DIR, base_name + ext)
            if os.path.exists(f):
                os.remove(f)
