// main.cpp
#include <iostream>
#include "frontend/parser/parser.tab.hh" // path used in your Makefile

int main(int argc, char** argv) {
    // Construct parser (class generated by Bison inside namespace dana)
    dana::parser parser;

    // Call parse() to run the parser. Parser will call the lexer (yylex).
    int res = parser.parse();

    if (res == 0) {
        std::cout << "Parsing finished: success (parse() returned 0)\n";
    } else {
        std::cerr << "Parsing finished: failure (parse() returned " << res << ")\n";
    }

    // If your parser stores/returns the AST you can retrieve it here.
    // For example, if you later add a getter like `parser.getProgram()`,
    // you could print or examine the AST (not assumed here).
    return res;
}

